version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'trendyol'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'admin'

  link-converter:
    depends_on:
      - db
    image: link-converter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
    volumes:
      - link-converter-db:/var/lib/mysql
    ports:
      - "8080:8080"
    restart: always
volumes:
  db_data: {}
  link-converter-db: {}